apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kg7s0sjqk-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:591e2f8b427f62583a439ae157f38699786f68aa@sha256:a28c1ec5ad50cfd091e0363415ac87f7afc5931e9d1ec9aa8eb7a9a5c85ee610
          name: container-image
